export interface TableSpec {
  readonly name: string
  readonly columns: readonly string[]
  readonly primaryKey: readonly string[]
  readonly d1Defaults?: Readonly<Record<string, unknown>>
  readonly booleans?: readonly string[]
  readonly bigintNumbers?: readonly string[]
  readonly json?: readonly string[]
  readonly timestamps?: readonly string[]
}

/** Foreign-key-safe order for the final D1 shape and PostgreSQL baseline. */
export const registryTables = [
  {
    name: 'applications',
    columns: [
      'id',
      'posting_url',
      'posting_url_normalized',
      'posting_fingerprint',
      'company',
      'role',
      'location',
      'application_status',
      'target_stage',
      'personal_priority',
      'follow_up_at',
      'applied_at',
      'listing_availability',
      'listing_confidence',
      'listing_reason_code',
      'listing_checked_at',
      'listing_closed_candidate_at',
      'listing_consecutive_closed_checks',
      'version',
      'updated_revision',
      'created_at',
      'updated_at',
    ],
    primaryKey: ['id'],
    timestamps: [
      'follow_up_at',
      'applied_at',
      'listing_checked_at',
      'listing_closed_candidate_at',
      'created_at',
      'updated_at',
    ],
  },
  {
    name: 'registry_sequence',
    columns: ['id', 'revision'],
    primaryKey: ['id'],
  },
  {
    name: 'listing_check_runs',
    columns: [
      'id',
      'trigger',
      'mode',
      'state',
      'selected_count',
      'checked_count',
      'open_count',
      'closed_count',
      'review_count',
      'error_count',
      'started_at',
      'completed_at',
      'failed_at',
      'failure_code',
      'failure_message',
    ],
    primaryKey: ['id'],
    d1Defaults: {
      failed_at: null,
      failure_code: null,
      failure_message: null,
    },
    timestamps: ['started_at', 'completed_at', 'failed_at'],
  },
  {
    name: 'application_activities',
    columns: [
      'id',
      'application_id',
      'kind',
      'actor',
      'source',
      'revision',
      'occurred_at',
      'payload',
    ],
    primaryKey: ['id'],
    json: ['payload'],
    timestamps: ['occurred_at'],
  },
  {
    name: 'application_labels',
    columns: ['application_id', 'label', 'created_at'],
    primaryKey: ['application_id', 'label'],
    timestamps: ['created_at'],
  },
  {
    name: 'application_notes',
    columns: [
      'id',
      'application_id',
      'kind',
      'body',
      'source',
      'created_at',
      'updated_at',
    ],
    primaryKey: ['id'],
    timestamps: ['created_at', 'updated_at'],
  },
  {
    name: 'application_compensations',
    columns: [
      'id',
      'application_id',
      'kind',
      'currency_code',
      'minimum_minor',
      'maximum_minor',
      'period',
      'raw_text',
      'source',
      'created_at',
      'updated_at',
    ],
    primaryKey: ['id'],
    bigintNumbers: ['minimum_minor', 'maximum_minor'],
    timestamps: ['created_at', 'updated_at'],
  },
  {
    name: 'application_listing_check_schedules',
    columns: [
      'application_id',
      'due_at',
      'lease_token',
      'lease_until',
      'attempt_count',
      'last_error',
      'updated_at',
    ],
    primaryKey: ['application_id'],
    timestamps: ['due_at', 'lease_until', 'updated_at'],
  },
  {
    name: 'idempotency_receipts',
    columns: [
      'idempotency_key',
      'request_hash',
      'scope',
      'application_id',
      'resource_id',
      'created_at',
    ],
    primaryKey: ['idempotency_key'],
    timestamps: ['created_at'],
  },
  {
    name: 'job_posting_snapshots',
    columns: [
      'id',
      'application_id',
      'requested_url',
      'final_url',
      'status',
      'fetched_at',
      'fetcher_version',
      'raw_object_key',
      'raw_sha256',
      'raw_byte_length',
      'raw_media_type',
      'normalized_object_key',
      'normalized_sha256',
      'normalized_byte_length',
      'normalized_media_type',
      'error_code',
      'error_message',
    ],
    primaryKey: ['id'],
    timestamps: ['fetched_at'],
  },
  {
    name: 'application_listing_checks',
    columns: [
      'id',
      'application_id',
      'run_id',
      'operation_id',
      'requested_url',
      'final_url',
      'provider',
      'outcome',
      'confidence',
      'recommended_action',
      'reason_code',
      'http_status',
      'evidence',
      'content_hash',
      'checker_version',
      'checked_at',
      'received_at',
      'next_check_at',
    ],
    primaryKey: ['id'],
    json: ['evidence'],
    timestamps: ['checked_at', 'received_at', 'next_check_at'],
  },
  {
    name: 'content_entries',
    columns: [
      'id',
      'application_id',
      'kind',
      'locale',
      'state',
      'head_revision_id',
      'approved_revision_id',
      'version',
      'created_at',
      'updated_at',
    ],
    primaryKey: ['id'],
    timestamps: ['created_at', 'updated_at'],
  },
  {
    name: 'content_revisions',
    columns: [
      'id',
      'content_entry_id',
      'revision_number',
      'parent_revision_id',
      'contract_id',
      'contract_version',
      'object_key',
      'sha256',
      'byte_length',
      'media_type',
      'source',
      'facts_release_id',
      'job_snapshot_id',
      'operation_id',
      'created_at',
    ],
    primaryKey: ['id'],
    timestamps: ['created_at'],
  },
  {
    name: 'cv_links',
    columns: [
      'id',
      'application_id',
      'content_entry_id',
      'current_revision_id',
      'token',
      'preview_token',
      'public_url',
      'enabled',
      'disabled_reason',
      'disabled_at',
      'publication_version',
      'version',
      'created_at',
      'updated_at',
    ],
    primaryKey: ['id'],
    booleans: ['enabled'],
    timestamps: ['disabled_at', 'created_at', 'updated_at'],
  },
  {
    name: 'generated_artifacts',
    columns: [
      'id',
      'cv_link_id',
      'content_revision_id',
      'kind',
      'status',
      'request_id',
      'renderer_version',
      'publication_version',
      'qr_target',
      'object_key',
      'sha256',
      'byte_length',
      'media_type',
      'error_code',
      'error_message',
      'generated_at',
      'created_at',
      'updated_at',
    ],
    primaryKey: ['id'],
    timestamps: ['generated_at', 'created_at', 'updated_at'],
  },
  {
    name: 'pdf_generation_outbox',
    columns: [
      'artifact_id',
      'application_id',
      'content_entry_id',
      'message_version',
      'attempts',
      'created_at',
      'updated_at',
      'last_attempt_at',
      'last_error',
      'dispatched_at',
    ],
    primaryKey: ['artifact_id'],
    timestamps: [
      'created_at',
      'updated_at',
      'last_attempt_at',
      'dispatched_at',
    ],
  },
] as const satisfies readonly TableSpec[]

export type RegistryTableName = (typeof registryTables)[number]['name']
