/**
 * Type-safe filtering, deterministic ordering, and page or cursor pagination
 * for ordinary and relational Drizzle queries.
 *
 * @packageDocumentation
 */

export { defaultCursorCodec } from './cursor/codec'
export type {
  CursorCodec,
  CursorPayload,
  CursorScalar,
  CursorStateCodec,
  CursorValueDescriptor,
  CursorValueType,
  SerializedCursorScalar,
} from './cursor/types'
export {
  QueryError,
  type QueryErrorCode,
  type QueryErrorOptions,
} from './error'
export type {
  AnyQueryField,
  ColumnCatalog,
  ColumnField,
  CountQueryField,
  CustomExpressionCursor,
  CustomExpressionOptions,
  EnumSortableOptions,
  ExpressionHelpers,
  ExpressionOptions,
  FieldIsSortable,
  FieldNameOf,
  FieldOperatorsOf,
  FieldOrigin,
  FieldOriginOf,
  FieldResultOf,
  FieldValueOf,
  ManyRelationField,
  ManyRelationFilterTools,
  ManyRelationOperators,
  ManyRelationOptions,
  NullPlacement,
  RelationHelpers,
  SortableOptions,
  VirtualQueryField,
} from './fields/index'
export type {
  AnyFilterOperator,
  AppendOperators,
  BigIntOperators,
  BinaryFilterCondition,
  BinaryFilterOperator,
  BinaryFilterOperatorCompileArguments,
  BinaryFilterOperatorOptions,
  BooleanOperators,
  ComparisonOperators,
  DateOperators,
  DefaultOperatorKind,
  DefaultOperators,
  EnumOperators,
  EqualityOperators,
  FilterCondition,
  FilterGroup,
  FilterNode,
  FilterOperatorAnnotations,
  FilterValueBinder,
  FilterValueDescriptor,
  FilterValueShape,
  NormalizeOperators,
  NullableOperators,
  NumberOperators,
  OperatorContext,
  OperatorName,
  OperatorRequest,
  OperatorRequests,
  OperatorValue,
  PickOperators,
  ReplaceOperator,
  TextOperators,
  TypedFilterCondition,
  TypedFilterGroup,
  TypedFilterNode,
  UnaryFilterCondition,
  UnaryFilterOperator,
  UnaryFilterOperatorCompileArguments,
  UnaryFilterOperatorOptions,
  WithoutOperators,
} from './filtering/index'
export {
  appendOperators,
  bigintOperators,
  binaryFilterOperator,
  booleanOperators,
  comparisonOperators,
  dateOperators,
  enumOperators,
  equalityOperators,
  normalizeOperators,
  nullableOperators,
  numberOperators,
  pickOperators,
  replaceOperator,
  textOperators,
  unaryFilterOperator,
  withoutOperators,
} from './filtering/index'
export type {
  Direction,
  EffectiveOrderTerm,
  OrderRequest,
} from './ordering/index'
export type {
  CursorPageInfo,
  CursorPaginationRequest,
  CursorPaginationRuntime,
  PageInfo,
  PagePaginationRequest,
  PaginationFinalizeContext,
  PaginationImplementation,
  PaginationInfoOf,
  PaginationKindOf,
  PaginationOptions,
  PaginationPageInfo,
  PaginationRequestOf,
  PaginationResolution,
  PaginationResolutionOf,
  PaginationResolveContext,
  QueryPage,
  ResolvedPaginationOptions,
} from './pagination/index'
export { cursorPagination, pagePagination } from './pagination/index'
export type {
  AnyQueryDefinition,
  DefineQueryFields,
  DefineQueryHelpers,
  DefineQueryOptions,
  QueryContext,
  QueryFieldInfo,
  QueryFilterOperatorInfo,
  QueryPageInfoOf,
  QueryRequest,
  QueryRequestOf,
  QueryResolution,
  QueryResolutionOf,
  QueryResolveOptions,
  QueryResolveOptionsOf,
  SortableFieldName,
} from './query/index'
export { defineQuery, QueryDefinition } from './query/index'
export {
  formatFilterExpression,
  formatSortExpression,
  maxCompactFilterLength,
  maxCompactSortLength,
  maxCompactSortTerms,
  parseFilterExpression,
  parseSortExpression,
  type QueryLanguageIssue,
  type QueryLanguageIssueCode,
  type QueryLanguageResult,
} from './query-language/index'
export {
  appendQueryParam,
  decodeFlatQueryParams,
  encodeFlatQueryParams,
  type FlatQueryParams,
  maxQueryFilterDepth,
  maxQueryFilterNodes,
  normalizeQueryFilterNodes,
  type QueryPaginationKind,
  type QuerySearchParamsInput,
  queryParamsFromRecord,
  queryParamsRecord,
  queryParamValues,
  replaceQueryParam,
  reservedQueryParameters,
} from './query-params/index'
export type { FinalizedPage } from './rendering/result'
export {
  type DynamicSelectBuilder,
  type FilteringFragments,
  type OrderingFragments,
  type PaginationFragments,
  type RelationalQueryConfig,
  type RelationalQueryView,
  type RequiredSelection,
  type ResolvedCursorState,
  ResolvedQuery,
  type SelectableExpressionName,
  type SelectQueryView,
} from './resolved-query'
