output "paths" {
  description = "Infisical paths managed by this module."
  value = {
    root      = local.root_path
    analytics = local.analytics_path
    content   = local.content_path
    deploy    = local.deploy_path
    grafana   = local.grafana_path
  }
}

output "placeholder_secrets" {
  description = "Secrets initialized with dummy values for a user to fill later."
  value = {
    for path, secrets in local.secret_shape :
    path => sort([
      for name, secret in secrets :
      name
      if secret.value == local.placeholder_value
    ])
  }
}

output "generated_secrets" {
  description = "Secrets generated by Terraform and written to Infisical."
  value = {
    (local.content_path) = [
      infisical_secret.content_id_salt.name,
      infisical_secret.private_audience_key.name,
      infisical_secret.private_content_root_key.name,
    ]
    (local.analytics_path) = [
      infisical_secret.grafana_connector_token.name,
    ]
  }
}
