output "paths" {
  description = "Infisical paths managed by this module."
  value = {
    root                 = local.root_path
    analytics            = local.analytics_path
    application_registry = local.application_registry_path
    content              = local.content_path
    deploy               = local.deploy_path
    facts_publication    = local.facts_publication_path
  }
}

output "placeholder_secrets" {
  description = "Secrets initialized with dummy values for a user to fill later."
  value = {
    for path, secrets in local.secret_shape :
    path => sort([
      for name, secret in secrets :
      name
      if secret.value == local.placeholder_value
    ])
  }
}

output "generated_secrets" {
  description = "Secrets generated by Terraform and written to Infisical."
  value = {
    (local.content_path) = [
      infisical_secret.private_audience_key.name,
    ]
    (local.application_registry_path) = [
      infisical_secret.registry_api_token.name,
    ]
    (local.facts_publication_path) = [
      infisical_secret.facts_publish_token.name,
    ]
  }
}
