/** Canonical registry path generated by the shared HTTP API declaration. */
export const applicationRegistryApiPrefix = '/api/registry' as const

/**
 * Bearer-only transport namespace for CLI and automation callers.
 *
 * The API server strips this prefix before invoking the canonical HTTP API.
 * Keeping it outside `/api/registry` lets Cloudflare Access bypass only machine
 * traffic without exposing the browser BFF's server-side token injection.
 */
export const applicationRegistryMachinePrefix = '/machine' as const

export const applicationRegistryMachineBaseUrl = (origin: URL): URL =>
  new URL(`${applicationRegistryMachinePrefix.slice(1)}/`, origin)
