import { HttpUrlSchema } from '@cv/application-registry-entity'
import { Schema } from 'effect'

/** Canonical registry path generated by the shared HTTP API declaration. */
export const applicationRegistryApiPrefix = '/api/registry' as const

/** A Registry connection accepts the same plain HTTP(S) URL model as the API. */
export const RegistryOriginSchema = HttpUrlSchema

export const normalizeRegistryOrigin = (input: string): string => {
  const url = new URL(Schema.decodeUnknownSync(RegistryOriginSchema)(input))
  url.pathname = '/'
  url.search = ''
  url.hash = ''
  return url.origin
}
