import type {
  CreateCampaignCaptureRequest,
  UpsertApplicationRequest,
} from '@cv/application-registry-api-contract'

export const applicationInput: UpsertApplicationRequest = {
  applicationStatus: 'not_started',
  appliedAt: null,
  canonicalUrl: 'https://example.com/jobs/e2e-registry',
  company: 'Example Company',
  compensations: [
    {
      currencyCode: 'JPY',
      kind: 'base_salary',
      maximumMinor: 15_000_000,
      minimumMinor: 10_000_000,
      period: 'year',
      rawText: 'JPY 10m–15m',
      source: 'e2e',
    },
  ],
  followUpAt: null,
  jobKey: 'url:https://example.com/jobs/e2e-registry',
  labels: ['e2e', 'remote'],
  lastContactAt: null,
  location: 'Tokyo or remote',
  personalPriority: 'high',
  role: 'Integration Engineer',
  source: 'e2e',
  sourceJobId: null,
  targetStage: 'apply_next',
}

export const captureInput: CreateCampaignCaptureRequest = {
  ...applicationInput,
  artifacts: [],
  applicationUrl: 'https://example.com/jobs/e2e-registry/apply',
  audience: null,
  campaignRunId: 'e2e-run',
  capturedAt: '2026-07-10T12:00:00.000Z',
  confidence: 0.8,
  deviceId: 'miniflare',
  fitAssessment: {
    dimensions: {
      coreExperience: 22,
      hardRequirements: 36,
      practicalEligibility: 9,
      preferredSignals: 8,
      seniorityAndScope: 13,
    },
    gaps: ['One preferred signal is not documented.'],
    hardBlockers: [],
    rationale: 'The authored evidence supports the core requirements.',
    rubricVersion: 'application-fit-v1',
    score: 88,
    strengths: ['Directly relevant implementation experience.'],
  },
  jobContentHash: null,
  operationId: 'e2e:capture:1',
  profile: 'default',
  submissionDetails: {
    additionalInstructions: null,
    applicationMethod: 'web form',
    applicationQuestions: [],
    contactEmail: null,
    coverLetterInstructions: null,
    deadline: null,
    employmentType: 'full-time',
    languageRequirements: ['English'],
    locationRestrictions: null,
    relocation: null,
    requiredDocuments: ['CV'],
    salary: null,
    visaRequirements: null,
    workMode: 'remote',
  },
}
